<?php

namespace Timetabler;

use Illuminate\Database\Eloquent\Model;
use Timetabler\Timetable\TimetableGenerator;

use Timetabler\Lectures;

class Session extends Model
{

    protected $table = "sessions";
    // protected $fillable = [
    //     "room_id", "period_id", "lecture_id", 'unit_id'
    // ];
    
    protected $guarded = [];
    
    function unoccupiedSessions(){
        // 'unit', 'room', 'lecture',  
        return $this->whereNull("unit_id") ->with('period', 'period.day');
        // ->groupBy('period_id');
    }
    

    function unit(){
        return $this->belongsTo(Unit::class, "unit_id", "id");
    }

    function room(){
        return $this->belongsTo(Room::class, "room_id", "id");
    }

    function period(){
        return $this->belongsTo(Period::class, "period_id", "id");
    }

    function lecture()
    {
        return $this->belongsTo(Lectures::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($session){
            //TimetableGenerator::addSession($session);
        });
    }
    
    /*check lec crushes 
        1.against themselves,
        2.against other lecturers.
    */
    
    

    public function checkCrushes($lecId, $sessionId)
    {
        # code...
    }
    
    function emptySessions(Room $room){
        return $room->unoccupiedSessions;
    }
    
}
